//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public int KullaniciId { get; set; }
        public string Email { get; set; }
        public string Ad { get; set; }
        public string Parola { get; set; }
        public System.DateTime Tarih { get; set; }
        public bool Onay { get; set; }
        public string Sayi { get; set; }
        public int MahalleId { get; set; }
        public string KullaniciResim { get; set; }
    }
}
