//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marketler
    {
        public int MarketId { get; set; }
        public string MarketAdi { get; set; }
        public int MahalleId { get; set; }
        public string Adres { get; set; }
        public int MarketEkleyen { get; set; }
    }
}
