//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class veritabaniEnucuzUrunEntities : DbContext
    {
        public veritabaniEnucuzUrunEntities()
            : base("name=veritabaniEnucuzUrunEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IzmitMahalle> IzmitMahalles { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
        public virtual DbSet<Marketler> Marketlers { get; set; }
        public virtual DbSet<Paylasimlar> Paylasimlars { get; set; }
        public virtual DbSet<Urunler> Urunlers { get; set; }
        public virtual DbSet<UrunTakip> UrunTakips { get; set; }
        public virtual DbSet<Yorumlar> Yorumlars { get; set; }
        public virtual DbSet<View_AnasayfaUrunTakipListe> View_AnasayfaUrunTakipListe { get; set; }
        public virtual DbSet<View_KullaniciBilgi> View_KullaniciBilgi { get; set; }
        public virtual DbSet<View_Marketler> View_Marketler { get; set; }
        public virtual DbSet<View_MarketUrunleri> View_MarketUrunleri { get; set; }
        public virtual DbSet<View_UrunlerMarketMahalle> View_UrunlerMarketMahalle { get; set; }
        public virtual DbSet<View_UrunMalumat> View_UrunMalumat { get; set; }
        public virtual DbSet<View_Yorumlar> View_Yorumlar { get; set; }
    }
}
