//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunTakip
    {
        public int TakipId { get; set; }
        public int KullaniciId { get; set; }
        public int BarkodId { get; set; }
        public bool Takip { get; set; }
    }
}
