//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int BarkodId { get; set; }
        public string Barkod { get; set; }
        public string UrunAd { get; set; }
        public int UrunIlkEkleyen { get; set; }
        public decimal EnUcuzFiyat { get; set; }
        public int MarketId { get; set; }
        public string BarkodTur { get; set; }
        public string UrunResim { get; set; }
    }
}
