//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_UrunMalumat
    {
        public string UrunAd { get; set; }
        public string MarketAdi { get; set; }
        public string Ad { get; set; }
        public int PaylasimId { get; set; }
        public int BarkodId { get; set; }
        public int KullaniciId { get; set; }
        public int MarketId { get; set; }
        public decimal Fiyat { get; set; }
        public System.DateTime Tarih { get; set; }
        public string UrunResim { get; set; }
        public string KullaniciResim { get; set; }
    }
}
