//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlar
    {
        public int YorumId { get; set; }
        public int BarkodId { get; set; }
        public string Yorum { get; set; }
        public System.DateTime Tarih { get; set; }
        public int KullaniciId { get; set; }
    }
}
